### ISSUE TITLE
淘宝故障

### ISSUE THREAD

**Issue by huajideshutiao** [jk278/Ad-J#2]
下面的是未启用规则
![Screenshot_2024-08-18-12-38-17-368_mark via](https://github.com/user-attachments/assets/0fd59e9f-05cd-43b6-b071-fd4c8d41a039)

下面的是启用规则
![Screenshot_2024-08-18-12-37-52-624_mark via](https://github.com/user-attachments/assets/ea9eb6d9-fb65-4509-9705-516887ec22d5)

是main.m.taobao.com##button这个规则的问题

**Comment by 0xjax** [comment]
感谢反馈，已更新
