### ISSUE TITLE
百度视频搜索结果误杀

### ISSUE THREAD

**Issue by Aloazny** [jk278/Ad-J#3]
百度搜索结果视频误杀 [链接](https://m.baidu.com/sf/vsearch?pd=video&word=%E6%89%8B%E6%9C%BA&tn=vsearch&sa=vs_tab&lid=11066458460938191280&ms=1&atn=index)

已经定位到误杀规则是
```
m.baidu.com##.c-video-container
```
建议大佬把规则写成
```
3g.baidu.com,m.baidu.com,m2.baidu.com,m3.baidu.com,m5.baidu.com##.ec_wise_ad
3g.baidu.com,m.baidu.com,m2.baidu.com,m3.baidu.com,m5.baidu.com##.c-video-container
3g.baidu.com,m.baidu.com,m2.baidu.com,m3.baidu.com,m5.baidu.com##.c-blocka ec_title
```

一条一条的写，不然误杀了，不方便放行😂。

**Comment by 0xjax** [comment]
你好，感谢你的反馈。
加入此规则是由于视频中包含较多推广内容，还无法关闭自动播放。
已采纳建议，把视频内容独列一行，方便放行。
如有更多建议，欢迎随时反馈。

**Comment by Aloazny** [comment]
好的，辛苦大佬了！

**Comment by Aloazny** [comment]
大佬，我看这个页面也没有自动播放啊。另外停用自动播放，好像其他规则早就写有了。

```
! 百度视频禁止自动播放
baidu.com##.c-video-player
baidu.com##[class^="cu-video-player"]
```

另外我想说的是这个，搜索下的图片全被杀了，可能会逼死强迫症😂。

![Screenshot_2024-09-18-11-26-01-764_mark.via.gq.jpg](https://github.com/user-attachments/assets/c2658066-86f0-4ded-bb82-53845909f9e0)

**Comment by 0xjax** [comment]
再次感谢指正！
```
baidu.com##.c-video-player
```
这条规则好像已经过时，只会导致视频搜索页误杀。已使用如下规则替代，效果是会删除（ublock origin 删除，adblock plus 阻止自动播放？）搜索“全部”页会自动播放的推荐视频块。
```
3g.baidu.com,m.baidu.com,m2.baidu.com,m3.baidu.com,m5.baidu.com##[srcid=vid_recommend]
```
如有更优雅的解决方式，随时欢迎交流。

**Comment by Aloazny** [comment]
这个有误杀？不太确定，我用了另一个大佬的规则挺久的了，没看到有什么误杀，搜索结果除了广告也都没少啥。
![Screenshot_2024-09-18-18-37-23-540_cn nr19 mbrowser](https://github.com/user-attachments/assets/0af261df-78d4-4e0a-9bb1-5af699a555ec)
![Screenshot_2024-09-18-18-41-39-399_cn nr19 mbrowser](https://github.com/user-attachments/assets/71e8e6fb-9a34-4cf7-baad-21415e66e1bb)
![Screenshot_2024-09-18-18-41-48-891_cn nr19 mbrowser](https://github.com/user-attachments/assets/111d7f0b-250b-47e2-a50c-5e972cf718a7)
